spring:
  datasource:
    url: jdbc:mysql://remotemysql.com/ynqv2VtHTp?serverTimezone=CET&createDatabaseIfNotExist=true
    username: ynqv2VtHTp
    password: ksqu3rMN4G
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
