spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/airport_flight_info?serverTimezone=CET
    username: root
    password: root1234
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
