spring:
  datasource:
    url: jdbc:mysql://eu-cdbr-west-01.cleardb.com/heroku_85258873ec623a5?reconnect=true
    username: ba37f26d9a6cc4
    password: c2eff91f
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
